[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov=blastula --cov-report=term-missing"
testpaths = ["blastula/tests"]

[project]
name = "blastula"
dynamic = ["version"]
description = "Easily send great-looking HTML email messages from Python."
readme = "README.md"
requires-python = ">=3.9"
license.file = "LICENSE"
dependencies = [
    "requests",
]

authors = [
    { name = "Jules Walzer-Goldfeld", email = "jules.walzergoldfeld@gmail.com"},
    { name = "Michael Chow", email = "mc_al_github@fastmail.com" },
    { name = "Rich Iannone", email = "rich@posit.co"}
]

classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
keywords = ["tables", "html"]

[dependency-groups]
dev = [
    "quartodoc>=0.8.1; python_version >= '3.9'",
    "griffe",
    "pytest>=3",
    "pytest-cov",
    "syrupy",
    "quartodoc>=0.11.1",
    "quarto>=0.1.0",
    "pre-commit>=4.2.0",
]


[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:"
]
include = ["blastula/*"]
omit = [
    "blastula/tests/*"
]